max_width = 120
fn_args_density = "Compressed"
fn_single_line = true
format_strings = true
hard_tabs = true
merge_imports = false
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
report_todo = "Unnumbered"
report_fixme = "Unnumbered"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
edition = "2018"
unstable_features = true
